### ISSUE TITLE
Using MoveIt crashes the game after a delay

### ISSUE THREAD

**Issue by OxygenIsCool** [Quboid/CS2-MoveIt#10]
[object Object]
Colossal.Logging.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogFormat(LogType, String, Object[])
Colossal.Logging.UnityLogger:Log(Level, String, Exception)
Colossal.Logging.UnityLogger:Error(Object)
QCommonLib.QLoggerCO:Error(String, String) (at E:\CS2Mods\QCommon\Repo\Code\QCommon\QCommon\Shared\QLogger.cs:356)
MoveIt.Overlays.Children.OverlaySegment:UpdateRelatedNodes() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Overlays\Children\OverlaySegment.cs:71)
MoveIt.Overlays.Children.OverlaySegment:DestroyOverlayEntity() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Overlays\Children\OverlaySegment.cs:51)
MoveIt.Overlays.Overlay:Dispose() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Overlays\Overlay.cs:202)
MoveIt.Moveables.Moveable:Dispose() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Moveables\Moveable.cs:251)
MoveIt.Moveables.MVSegment:Dispose() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Moveables\MVSegment.cs:147)
MoveIt.Managers.MoveablesManager:RemoveDo(Moveable) (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Managers\MoveablesManager.cs:300)
MoveIt.Managers.MoveablesManager:Refresh() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Managers\MoveablesManager.cs:120)
MoveIt.Tool.MIT:OnStartRunning() (at E:\CS2Mods\MoveIt\Repo-Public\Code\MoveIt\Tool\Lifecycle.cs:96)
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.Tools.ToolSystem:ToolUpdate()
Game.Tools.ToolSystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.SceneFlow.GameManager:UpdateWorld()
Game.SceneFlow.GameManager:Update()

I've noticed that using Move It will cause the game to crash after about 5 minutes since using the tool. I've been able to replicate this twice. The tool itself works in-game, but the crash forces me to restart the game. I've included the log report .zip file.

Great mod, hope you can find a fix!

[MoveIt_Logs_2024-12-14_12_11_52.zip](https://github.com/user-attachments/files/18135099/MoveIt_Logs_2024-12-14_12_11_52.zip)

**Comment by OxygenIsCool** [comment]
I'd also like to add I've only tried re-creating by using the tool on road splines.

**Comment by Quboid** [comment]
Thanks for the log, this has been fixed in 0.5.2.
